apiVersion: apps/v1
kind: Deployment
metadata:
  name: trial-app
  annotations:
    sidecar.jaegertracing.io/inject: "true"
  labels:
    app: trial
spec:
  replicas: 3
  selector:
    matchLabels:
      app: trial
  template:
    metadata:
      labels:
        app: trial
    spec:
      containers:
        - name: trial
          image: minorpatch/metrics-dashboard-trial:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: trial-service
  labels:
    app: trial
spec:
  selector:
    app: trial
  ports:
    - name: trial
      port: 8083
      targetPort: 8080
  type: LoadBalancer
