apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: frontend
  namespace: monitoring
  labels:
    app: frontend
    release: prometheus
spec:
  selector:
    matchLabels:
      app: frontend
  endpoints:
    - port: frontend
      path: /metrics
  namespaceSelector:
    matchNames:
      - default
      - monitoring
      - observability